import os
from datetime import datetime

START_DATE = "2022-01-01"
END_DATE   = datetime.now().strftime('%Y-%m-%d')

STOCKS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS",
    "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
    "RELIANCE.NS", "ONGC.NS", "POWERGRID.NS", "NTPC.NS", "BPCL.NS",
    "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS",
    "MARUTI.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "APOLLOHOSP.NS",
    "MPHASIS.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "TATAELXSI.NS",
    "BAJAJFINSV.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS", "MANAPPURAM.NS", "SBILIFE.NS",
    "MOTHERSON.NS", "BALKRISIND.NS", "BHARATFORG.NS", "ESCORTS.NS", "TIINDIA.NS",
    "LT.NS", "ADANIPORTS.NS", "IRCTC.NS", "BEL.NS", "HAL.NS",
    "PIDILITIND.NS", "AARTIIND.NS", "DEEPAKNTR.NS", "TATACHEM.NS", "GNFC.NS",
    "DLF.NS", "GODREJPROP.NS", "ULTRACEMCO.NS", "AMBUJACEM.NS", "SHREECEM.NS",
    "TRENT.NS", "DMART.NS", "NYKAA.NS", "TITAN.NS", "JUBLFOOD.NS",
    "DATAPATTNS.NS", "COCHINSHIP.NS", "MAZDOCK.NS",
    "ADANIGREEN.NS", "TATAPOWER.NS", "CESC.NS", "SJVN.NS", "NHPC.NS",
    "PAYTM.NS", "POLICYBZR.NS", "ZOMATOLTD.NS", "NAUKRI.NS", "INDIAMART.NS",
    "NAVINFLUOR.NS", "FINEORG.NS", "VINATIORGA.NS", "SUDARSCHEM.NS",
    "BANKBARODA.NS", "CANBK.NS", "FEDERALBNK.NS", "AUBANK.NS", "IDFCFIRSTB.NS",
    "MAXHEALTH.NS", "FORTIS.NS", "METROPOLIS.NS", "THYROCARE.NS",
    "DELHIVERY.NS", "BLUEDART.NS", "INDIGO.NS", "IRFC.NS",
    "BAJFINANCE.NS", "HDFCLIFE.NS", "ICICIPRULI.NS", "ICICIGI.NS", "LTTS.NS",
]

GLOBAL_INDICES = [
    "^GSPC", "^DJI", "^IXIC", "^N225",
    "^NSEI", "^BSESN", "GC=F", "CL=F", "USDINR=X"
]

ALL_TICKERS = STOCKS + GLOBAL_INDICES

DB_NAME         = os.getenv("DB_NAME", "quantsense")
COLLECTION_NAME = os.getenv("COLLECTION_NAME", "stock_prices")
MONGO_URL       = os.getenv("MONGO_URL", "mongodb://localhost:27017/")